apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-auth
  template:
    metadata:
      labels:
        app: ms-auth
    spec:
      containers:
        - name: ms-auth
          image: devcoderjava/ms-auth:latest
          ports:
            - containerPort: 9000
          env:
            - name: LB_USERS_URI
              valueFrom:
                configMapKeyRef:
                  key: lb_users_uri
                  name: ms-users
---
apiVersion: v1
kind: Service
metadata:
  name: svc-auth
spec:
  type: LoadBalancer
  ports:
    - port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: ms-auth

