apiVersion: apps/v1
kind: Deployment
metadata:
  name: msvc-courses
spec:
  replicas: 1
  selector:
    matchLabels:
      app: msvc-courses
  template:
    metadata:
      labels:
        app: msvc-courses
    spec:
      containers:
        - name: courses
          image: devcoderjava/courses:latest
          ports:
            - containerPort: 8002
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  key: port
                  name: ms-courses
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  key: db_host
                  name: ms-courses
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  key: database
                  name: ms-courses
            - name: DB_USERNAME
              valueFrom:
                configMapKeyRef:
                  key: username
                  name: ms-courses
            - name: DB_PASSWORD
              valueFrom:
                configMapKeyRef:
                  key: password
                  name: ms-courses
            - name: USUARIOS_URL
              valueFrom:
                configMapKeyRef:
                  key: usuarios_url
                  name: ms-courses
