apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-api-gateway
  template:
    metadata:
      labels:
        app: ms-api-gateway
    spec:
      containers:
        - name: ms-api-gateway
          image: devcoderjava/ms-api-gateway-guz:latest
          ports:
            - containerPort: 8090
---
apiVersion: v1
kind: Service
metadata:
  name: svc-api-gateway
spec:
  type: LoadBalancer
  ports:
    - port: 8090
      protocol: TCP
      targetPort: 8090
  selector:
    app: ms-api-gateway

